'use client';
import Image from 'next/image';
import { useState, useRef, useEffect, type ReactNode } from 'react';
import { motion, useReducedMotion, useMotionValue, useSpring } from 'framer-motion';
import { ArrowUpRight, ArrowRight, Plus, Menu, X, Layers, Diamond, CreditCard, Box, Globe2, ChartNoAxesCombined, Coins, Banknote, Zap, Shuffle, ShieldCheck, ScanLine, Check, Send, MoveUpRight } from 'lucide-react';
const BOT = 'https://t.me/houseofstarsorderbot';
const nav = [['How It Works', '#how-it-works'], ['Assets', '#assets'], ['Payouts', '#payouts'], ['Why House of Stars', '#why'], ['FAQ', '#faq']];
function Star({ className = '' }: {
    className?: string;
}) { return <svg className={className} viewBox="0 0 64 64" fill="none" aria-hidden="true"><path d="M32 2L39.5 24.5L62 32L39.5 39.5L32 62L24.5 39.5L2 32L24.5 24.5L32 2Z" fill="currentColor"/><path d="M12 12L32 23L52 12L41 32L52 52L32 41L12 52L23 32Z" fill="currentColor" opacity=".45"/></svg>; }
function BrandMark({ className = '' }: { className?: string }) {
  return <Image src="/house-of-stars-logo.jpg" alt="" width={400} height={400} className={`brand-mark ${className}`} unoptimized />;
}
function Logo() { return <a className="logo" href="#" aria-label="House of Stars home"><BrandMark /><span>HOUSE OF STARS</span></a>; }
function CTA({ children = 'Open Exchange', className = '' }: {
    children?: ReactNode;
    className?: string;
}) { return <a className={`button ${className}`} href={BOT} target="_blank" rel="noopener noreferrer">{children}<ArrowUpRight size={17}/></a>; }
function Reveal({ children, className = '', delay = 0 }: {
    children: ReactNode;
    className?: string;
    delay?: number;
}) { const reduced = useReducedMotion(); return <motion.div className={className} initial={reduced ? false : { opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: '-40px' }} transition={{ duration: .65, delay }}>{children}</motion.div>; }
function Label({ children }: {
    children: ReactNode;
}) { return <div className="eyebrow"><span />{children}</div>; }
const incoming = [{ name: 'Digital assets', icon: Layers }, { name: 'Credits', icon: CreditCard }, { name: 'Collectibles', icon: Diamond }, { name: 'Alternative assets', icon: Box }, { name: 'Other supported assets', icon: Globe2 }];
function ExchangeGraphic({ engine = false }: {
    engine?: boolean;
}) {
    const reduced = useReducedMotion();
    const [active, setActive] = useState<number | null>(null);
    const x = useMotionValue(0);
    const y = useMotionValue(0);
    const sx = useSpring(x, { stiffness: 65, damping: 22 });
    const sy = useSpring(y, { stiffness: 65, damping: 22 });
    return <motion.div className={`exchange-graphic ${engine ? 'engine-graphic' : ''}`} style={{ rotateY: sx, rotateX: sy }} onPointerMove={e => { if (reduced || e.pointerType !== 'mouse')
        return; const r = e.currentTarget.getBoundingClientRect(); x.set((e.clientX - r.left - r.width / 2) / 90); y.set(-(e.clientY - r.top - r.height / 2) / 90); }} onPointerLeave={() => { x.set(0); y.set(0); }}>
 <div className="diagram-caption"><span>ILLIQUID ASSETS<span className="caption-correction"> / INPUT</span></span><span>LIQUID VALUE / OUTPUT</span></div>
 <svg className="routes" viewBox="0 0 700 460" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id={engine ? 'route-e' : 'route-h'}><stop stopColor="#cfff47" stopOpacity=".08"/><stop offset=".7" stopColor="#cfff47" stopOpacity=".65"/><stop offset="1" stopColor="#cfff47" stopOpacity=".2"/></linearGradient></defs>{[85, 155, 225, 295, 365].map((v, i) => <g key={v}><path className={`route ${active === i ? 'route-active' : ''}`} d={`M 140 ${v} C 250 ${v}, 230 225, 350 225`} stroke={`url(#${engine ? 'route-e' : 'route-h'})`}/><path className="flow" style={{ animationDelay: `${i * -.7}s` }} d={`M 140 ${v} C 250 ${v}, 230 225, 350 225`}/></g>)}{[135, 225, 315].map((v, i) => <g key={v}><path className={`route output-route ${active !== null ? 'route-active' : ''}`} d={`M 350 225 C 470 225, 460 ${v}, 575 ${v}`}/><path className="flow" style={{ animationDelay: `${i * -.9}s` }} d={`M 350 225 C 470 225, 460 ${v}, 575 ${v}`}/></g>)}</svg>
 <div className="orbital-ring ring-one"/><div className="orbital-ring ring-two"/><div className="orbital-ring ring-three"/>
 <div className="exchange-core"><div className="core-shine"/><BrandMark /><span>HOUSE OF STARS</span><small>EXCHANGE</small></div>
 <div className="asset-nodes">{incoming.map(({ name, icon: Icon }, i) => <button key={name} onFocus={() => setActive(i)} onBlur={() => setActive(null)} onMouseEnter={() => setActive(i)} onMouseLeave={() => setActive(null)} className={`asset-node asset-${i} ${active === i ? 'selected' : ''}`}><Icon size={15}/><span>{engine && i === 4 ? 'Marketplace value' : name}</span><span className="node-dot"/></button>)}</div>
 <div className="output-nodes">{[{ name: 'STOCKS', icon: ChartNoAxesCombined }, { name: 'CRYPTO', icon: Coins }, { name: 'FIAT', icon: Banknote }].map(({ name, icon: Icon }, i) => <a href="#payouts" className={`output-node output-${i}`} key={name}><Icon size={18}/><span>{name}</span><ArrowUpRight size={12}/></a>)}</div>
 <div className="diagram-bottom"><span><i /> A NEW PATH FOR YOUR VALUE</span><span>01 — 03 <ArrowRight size={13}/></span></div>
 </motion.div>;
}
const payouts = [{ name: 'Stocks', tag: 'MARKET ACCESS', icon: ChartNoAxesCombined, text: 'Move value into supported stocks and market assets.' }, { name: 'Crypto', tag: 'ON-CHAIN VALUE', icon: Coins, text: 'Withdraw through supported cryptocurrencies and blockchain networks.' }, { name: 'Fiat', tag: 'EVERYDAY LIQUIDITY', icon: Banknote, text: 'Receive value through supported fiat payout methods.' }];
const faq = [['What is an illiquid asset?', 'An illiquid asset is something that has value but cannot always be sold quickly or easily because there may be fewer buyers, fragmented marketplaces, restrictions, or limited ways to cash out.'], ['What does House of Stars do?', 'House of Stars provides an exchange layer designed to help users convert supported illiquid assets into more usable forms of value.'], ['How can I withdraw?', 'Depending on the asset and order, supported payout options can include stocks, cryptocurrency, or fiat.'], ['Where do I start an order?', 'Orders begin through the official House of Stars Telegram bot.'], ['Are all assets supported?', "No. Availability can depend on the asset, market conditions, liquidity, location, and House of Stars’ current support."], ['Is the quoted value guaranteed?', 'Quotes, availability, processing requirements and final settlement may depend on the specific asset and transaction conditions.']];
export default function Home() {
    const [menu, setMenu] = useState(false);
    const [payout, setPayout] = useState(0);
    const [legal, setLegal] = useState<string | null>(null);
    const closeRef = useRef<HTMLButtonElement>(null);
    useEffect(() => { if (!legal)
        return; const previous = document.activeElement as HTMLElement; const overflow = document.body.style.overflow; document.body.style.overflow = 'hidden'; closeRef.current?.focus(); return () => { document.body.style.overflow = overflow; previous?.focus(); }; }, [legal]);
    useEffect(() => { if (!menu)
        return; const close = (event: KeyboardEvent) => { if (event.key === 'Escape')
        setMenu(false); }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, [menu]);
    return <><a href="#main" className="skip-link">Skip to content</a><header className="header"><div className="contract-bar"><span className="contract-label">CA:</span><span className="contract-address">0x16d5f49CeAC446817cbAa83748B370d1cD833f5F</span></div><div className="nav-wrap"><Logo /><nav aria-label="Main navigation">{nav.map(([n, h]) => <a key={n} href={h}>{n}</a>)}</nav><CTA /><button className="menu-toggle" aria-label={menu ? 'Close menu' : 'Open menu'} aria-expanded={menu} aria-controls="mobile-menu" onClick={() => setMenu(!menu)}>{menu ? <X /> : <Menu />}</button></div>{menu && <nav id="mobile-menu" className="mobile-nav" aria-label="Mobile navigation">{nav.map(([n, h]) => <a key={n} href={h} onClick={() => setMenu(false)}>{n}<ArrowUpRight size={16}/></a>)}<CTA /></nav>}</header>
 <main id="main"><section className="hero section-shell"><div className="hero-grid"/><div className="hero-glow"/><div className="hero-layout"><Reveal className="hero-copy"><Label>VALUE, UNLOCKED.</Label><h1>Turn hard-to-sell<br />assets into<br /><span>liquid value.</span></h1><p className="hero-lead">Liquidity for the things that are hard to sell.</p><p className="hero-description">House of Stars is an exchange for illiquid assets. Convert value that’s difficult to sell into something you can actually use — through stocks, crypto, or fiat.</p><div className="hero-buttons"><CTA>Start Trading</CTA><a className="text-link" href="#how-it-works">See how it works <ArrowRight size={16}/></a></div><div className="hero-trust"><span className="mini-stars">✦ ✦ ✦</span><span>One exchange. Multiple ways to exit.</span></div></Reveal><Reveal className="hero-visual" delay={.2}><ExchangeGraphic /></Reveal></div><div className="hero-footer"><a href="#assets"><span className="scroll-icon">↓</span> SCROLL TO EXPLORE</a><span>BUILT FOR VALUE THAT DOESN’T FIT THE MOLD <Star /></span></div></section>
 <div className="asset-strip"><span>DIFFERENT ASSETS.<br /><strong>ONE LIQUIDITY LAYER.</strong></span>{incoming.slice(0, 4).map(({ name, icon: Icon }) => <div key={name}><Icon size={20}/>{name}<Plus size={13}/></div>)}</div>
 <section id="assets" className="section-shell problem"><Reveal className="section-heading"><Label>01 / THE LIQUIDITY GAP</Label><div className="split-heading"><h2>Value isn’t always<br />the same as <span>liquidity.</span></h2><p>An asset can be valuable and still be difficult to sell. The difference? How easily you can turn it into something you can use.</p></div></Reveal><div className="comparison-visual"><Reveal className="liquidity-panel"><div className="panel-top"><span className="status-dot"/>FREE TO MOVE<span>01</span></div><div className="stream-graphic" aria-hidden="true">{[0, 1, 2, 3, 4].map(i => <div key={i} style={{ '--i': i } as React.CSSProperties}/>)}<Star /></div><h3>Liquid assets</h3><p>Easy to buy, sell, or convert quickly.</p><div className="tags"><span>Cash</span><span>Major stocks</span><span>Major cryptocurrencies</span></div></Reveal><Reveal className="liquidity-panel illiquid-panel" delay={.1}><div className="panel-top"><span className="status-dot muted"/>VALUE, WAITING<span>02</span></div><div className="barrier-graphic" aria-hidden="true"><div className="value-cube cube-1"><Diamond /></div><div className="value-cube cube-2"><Box /></div><div className="value-cube cube-3"><Layers /></div><div className="barrier"/><ArrowRight className="barrier-arrow"/></div><h3>Illiquid assets</h3><p>It has value — but finding a buyer and converting that value can take time.</p><div className="tags"><span>Credits</span><span>Collectibles</span><span>Niche digital assets</span><span>Alternative assets</span></div></Reveal></div><Reveal className="bridge-line"><Star /><p>We exist to bridge <span>that liquidity gap.</span></p><ArrowDownBridge /></Reveal></section>
 <section id="how-it-works" className="section-shell how"><Reveal className="section-heading"><Label>02 / A SIMPLER WAY FORWARD</Label><h2>From asset <span>to liquidity.</span></h2><p>Three steps. More possibilities for your value.</p></Reveal><div className="steps">{[{ n: '01', title: 'Submit', text: 'Choose the asset you want to exchange and start an order through House of Stars.', icon: Layers }, { n: '02', title: 'Exchange', text: 'House of Stars processes your asset and converts its value through our exchange infrastructure.', icon: Shuffle }, { n: '03', title: 'Withdraw', text: 'Choose how you want to receive your value. Your asset, your next move.', icon: MoveUpRight }].map(({ n, title, text, icon: Icon }, i) => <Reveal className="step" key={n} delay={i * .1}><div className="step-number">{n}<span /><Icon size={22}/></div><h3>{title}</h3><p>{text}</p>{i === 0 ? <a href={BOT} target="_blank" rel="noopener noreferrer" className="text-link lime">Start an order <ArrowUpRight size={16}/></a> : i === 1 ? <div className="processing"><span /><span /><span /><ArrowRight size={14}/></div> : <div className="step-tags">STOCKS <span>/</span> CRYPTO <span>/</span> FIAT</div>}</Reveal>)}</div>
 <div id="payouts" className="payout-heading"><Label>YOUR VALUE. YOUR DESTINATION.</Label><p>Three ways to make your next move.</p></div><div className="payouts">{payouts.map(({ name, tag, icon: Icon, text }, i) => <Reveal key={name} delay={i * .1} className={`payout-card ${payout === i ? 'active' : ''}`}><button className="payout-select" onClick={() => setPayout(i)} aria-pressed={payout === i} aria-label={`Explore ${name} payouts`}><span>{tag}</span><ArrowUpRight size={19}/></button><div className={`payout-art art-${i}`} aria-hidden="true">{i === 0 ? <svg viewBox="0 0 320 120"><defs><linearGradient id="chart-fill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#cfff47" stopOpacity=".22"/><stop offset="1" stopColor="#cfff47" stopOpacity="0"/></linearGradient></defs><path d="M0 100L28 85L49 90L77 62L103 73L128 54L150 65L176 39L202 47L230 21L249 31L279 10L320 2V120H0Z" fill="url(#chart-fill)"/><path className="chart-line" d="M0 100L28 85L49 90L77 62L103 73L128 54L150 65L176 39L202 47L230 21L249 31L279 10L320 2"/></svg> : i === 1 ? <div className="crypto-orbits"><span>₿</span><span>Ξ</span><span>₮</span><i /><i /></div> : <div className="fiat-visual"><div><Star /><span>AVAILABLE VALUE</span><strong>Made to move.</strong><span>•••• &nbsp; HOUSE OF STARS <ArrowUpRight size={14}/></span></div><div /></div>}</div><div className="payout-title"><Icon size={24}/><h3>{name}</h3></div><p>{text}</p><span className="payout-availability">{payout === i ? 'Selected destination · Subject to order availability' : 'Available for supported orders'}</span></Reveal>)}</div><div className="payout-bottom"><span>You choose the exit.</span><CTA>Open House of Stars</CTA></div></section>
 <section className="engine section-shell"><Reveal className="engine-copy"><Label>03 / THE HOUSE OF STARS ENGINE</Label><h2>A liquidity layer<br />for <span>difficult assets.</span></h2><p>Different markets. Fragmented value. One place to bring it all together.</p><p className="small-copy">We connect supported assets to more usable forms of value, creating a path beyond the limitations of traditional marketplaces.</p><div className="engine-note"><ScanLine size={17}/> Explore an asset to follow its path.</div></Reveal><Reveal className="engine-diagram"><ExchangeGraphic engine/></Reveal></section>
 <section id="why" className="section-shell why"><Reveal className="section-heading"><Label>04 / BUILT AROUND YOUR VALUE</Label><h2>More possibility.<br /><span>Less getting stuck.</span></h2></Reveal><div className="feature-grid">{[{ icon: Zap, title: 'More liquidity', text: 'Turn assets with limited buyers into usable value.' }, { icon: Shuffle, title: 'Multiple exits', text: 'Choose between stocks, crypto, or fiat instead of being locked into one withdrawal method.' }, { icon: Send, title: 'Simple execution', text: 'Start your order through Telegram without navigating complicated trading interfaces.' }, { icon: Globe2, title: 'Built for difficult markets', text: 'Focused on assets traditional exchanges and marketplaces often don’t handle efficiently.' }, { icon: ChartNoAxesCombined, title: 'Fast experience', text: 'A streamlined process designed to reduce friction between holding value and using it.' }, { icon: Layers, title: 'One exchange', text: 'Bring different forms of value into one liquidity ecosystem.' }].map(({ icon: Icon, title, text }, i) => <Reveal key={title} className="feature" delay={(i % 3) * .08}><Icon size={24}/><h3>{title}</h3><p>{text}</p></Reveal>)}</div></section>
 <section className="section-shell route-comparison"><Reveal><Label>A SHORTER PATH</Label><h2>Same starting point.<br /><span>A different way out.</span></h2><p>Traditional selling vs. House of Stars.</p></Reveal><Reveal className="route-table"><div className="traditional-route"><h3>The traditional route</h3><div>{['Asset', 'List it', 'Wait for buyer', 'Negotiate', 'Marketplace limitations', 'Limited withdrawals'].map((s, i) => <span key={s}>{s}{i < 5 && <ArrowRight size={13}/>}</span>)}</div></div><div className="hos-route"><h3><BrandMark />House of Stars</h3><div><span>Your asset</span><ArrowRight /><span className="route-brand"><BrandMark />House of Stars</span><ArrowRight /><span>Stocks / Crypto / Fiat</span></div></div><p>Less friction between owning value and using it.</p></Reveal></section>
 <section className="telegram section-shell"><Reveal className="telegram-copy"><Label>05 / MEET YOUR EXCHANGE</Label><h2>Your next move.<br /><span>One conversation away.</span></h2><h3>Your exchange starts inside Telegram.</h3><p>Access House of Stars directly through our Telegram bot and start an order without downloading another trading app.</p><CTA>Launch Telegram Bot</CTA><span className="telegram-handle"><Send size={13}/> @houseofstarsorderbot</span></Reveal><Reveal className="chat-wrap"><div className="chat"><div className="chat-header"><div className="chat-avatar"><BrandMark /></div><div><strong>House of Stars <span>✓</span></strong><small>Official exchange bot</small></div><span className="chat-dots">•••</span></div><div className="chat-body"><span className="chat-date">YOUR VALUE STARTS HERE</span><div className="chat-bubble user-bubble">I want to exchange an asset <small>12:04 <Check size={12}/></small></div><div className="chat-bubble bot-bubble">Let’s put your value in motion.<br /><strong>Select your asset type</strong><small>12:04</small></div><div className="chat-options"><span>Digital assets</span><span>Credits</span><span>Collectibles</span><span>Other assets</span></div><div className="chat-divider"><span />ASSET REVIEWED<span /></div><div className="chat-bubble bot-bubble">Your next move is yours.<br /><strong>Choose your withdrawal method</strong><small>12:05</small></div><div className="chat-payouts">{payouts.map(({ name, icon: Icon }, i) => <button key={name} onClick={() => setPayout(i)} aria-pressed={payout === i} className={payout === i ? 'chosen' : ''}><Icon size={15}/>{name}</button>)}</div><div className="chat-selection"><Check size={12}/>{payouts[payout].name} selected for this preview</div></div><div className="chat-disclaimer">ILLUSTRATIVE PREVIEW · START REAL ORDERS IN TELEGRAM</div></div><div className="chat-orbit"/></Reveal></section>
 <section className="transparency section-shell"><Reveal className="split-heading"><div><Label>CLARITY AT EVERY STEP</Label><h2>Know what happens<br />to <span>your value.</span></h2></div><p>Before proceeding, review the information relevant to your order. A clearer exchange starts with informed decisions.</p></Reveal><div className="trust-grid">{[{ icon: ScanLine, title: 'Transparent quotes', text: 'Review the relevant exchange terms before proceeding.' }, { icon: ShieldCheck, title: 'Order tracking', text: 'Check the progress of your transaction through the exchange process.' }, { icon: Shuffle, title: 'Clear payout options', text: 'Confirm which payout methods are available for your order.' }].map(({ icon: Icon, title, text }) => <Reveal key={title}><Icon /><h3>{title}</h3><p>{text}</p></Reveal>)}</div></section>
 <section id="faq" className="faq section-shell"><Reveal><Label>A LITTLE MORE CLARITY</Label><h2>Good questions.<br /><span>Clear answers.</span></h2><p>Still curious? Start a conversation.</p><a href={BOT} target="_blank" rel="noopener noreferrer" className="text-link lime">Talk to House of Stars <ArrowUpRight size={15}/></a></Reveal><div className="faq-list">{faq.map(([q, a], i) => <Reveal key={q} delay={i * .03}><details><summary>{q}<Plus size={19}/></summary><div className="faq-answer"><p>{a}</p>{i === 3 && <a href={BOT} target="_blank" rel="noopener noreferrer">Open the official Telegram bot <ArrowUpRight size={14}/></a>}</div></details></Reveal>)}</div></section>
 <section className="final-cta section-shell"><div className="final-orbit"/><Reveal><BrandMark className="final-brand"/><Label>YOUR VALUE HAS A NEXT CHAPTER.</Label><h2>Make your value <span>liquid.</span></h2><p>Trade supported illiquid assets and choose how you want to exit.</p><div className="final-flow"><span>YOUR ASSET</span><ArrowRight /><span>HOUSE OF STARS</span><ArrowRight /><span>STOCKS / CRYPTO / FIAT</span></div><CTA>Start an Order</CTA><small>Powered through the House of Stars Telegram exchange experience.</small></Reveal></section>
 </main><footer className="section-shell"><div className="footer-main"><div><Logo /><p>The exchange for illiquid assets.</p></div><div className="footer-links"><span>EXPLORE</span>{nav.filter(([n]) => n !== 'Why House of Stars').map(([n, h]) => <a key={n} href={h}>{n}</a>)}</div><div className="footer-links"><span>PRODUCT</span><a href={BOT} target="_blank" rel="noopener noreferrer">Telegram Exchange <ArrowUpRight size={13}/></a><a href="https://github.com/Tenertheprodigy/House-Of-Stars" target="_blank" rel="noopener noreferrer">GitHub <ArrowUpRight size={13}/></a><span className="footer-note">One exchange.<br />Multiple ways to exit.</span></div><div className="footer-links"><span>LEGAL</span>{['Terms of Service', 'Privacy Policy', 'Risk Disclosure'].map(n => <button key={n} onClick={() => { setLegal(n); }}>{n} <span className="soon">Coming soon</span></button>)}</div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} House of Stars. All rights reserved.</span><span>VALUE, IN MOTION. <Star /></span></div></footer>
 {legal && <div className="modal-overlay" onClick={() => setLegal(null)}><div role="dialog" aria-modal="true" aria-labelledby="legal-title" className="legal-dialog" onClick={e => e.stopPropagation()} onKeyDown={e => { if (e.key === 'Escape')
        setLegal(null); if (e.key === 'Tab') {
        e.preventDefault();
        closeRef.current?.focus();
    } }}><button ref={closeRef} aria-label="Close dialog" onClick={() => setLegal(null)}><X /></button><Label>DOCUMENT PLACEHOLDER</Label><h2 id="legal-title">{legal}</h2><p>This document has not been published yet. Review the applicable terms, payout availability, and transaction conditions with House of Stars before placing an order.</p></div></div>}
 </>;
}
function ArrowDownBridge() { return <svg width="40" height="40" viewBox="0 0 40 40" fill="none" aria-hidden="true"><path d="M20 4V34M9 23L20 34L31 23" stroke="currentColor" strokeWidth="1"/></svg>; }
