'use client';

import { useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowUpRight, BookOpen, ChevronRight, Menu, X } from 'lucide-react';

const sections = [
  { title: 'Getting started', links: [{ id: 'overview', label: 'Overview' }, { id: 'how-it-works', label: 'How it works' }] },
  { title: 'Guides', links: [{ id: 'sell-stars', label: 'Sell Telegram Stars' }, { id: 'safety', label: 'Safety & support' }] },
  { title: 'About', links: [{ id: 'roadmap', label: 'Roadmap' }] },
];

export default function DocsPage() {
  const [active, setActive] = useState('overview');
  const [open, setOpen] = useState(false);
  const navigate = (id: string) => { setActive(id); setOpen(false); document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' }); };
  return <div className="docs-page">
    <header className="docs-topbar"><Link className="docs-brand" href="/"><span className="docs-mark">✦</span> HOUSE OF STARS <span className="docs-brand-sub">/ DOCS</span></Link><div className="docs-top-actions"><a href="https://t.me/houseofstarsorderbot" target="_blank" rel="noreferrer">Open Telegram bot <ArrowUpRight size={15}/></a><Link href="/">Back to website <ArrowLeft size={15}/></Link><button className="docs-menu-button" onClick={() => setOpen(!open)} aria-label="Toggle documentation menu">{open ? <X/> : <Menu/>}</button></div></header>
    <div className="docs-layout">
      <aside className={`docs-sidebar ${open ? 'docs-sidebar-open' : ''}`}><div className="docs-sidebar-label"><BookOpen size={15}/> DOCUMENTATION</div>{sections.map(group => <div className="docs-nav-group" key={group.title}><h2>{group.title}</h2>{group.links.map(item => <button key={item.id} className={active === item.id ? 'active' : ''} onClick={() => navigate(item.id)}>{item.label}{active === item.id && <ChevronRight size={14}/>}</button>)}</div>)}<div className="docs-sidebar-note">House of Stars<br/><span>Product guide · Updated Q4 2026</span></div></aside>
      <main className="docs-content"><div className="docs-breadcrumb">Docs <ChevronRight size={13}/> Getting started</div>
        <section id="overview" className="docs-section"><div className="docs-eyebrow">HOUSE OF STARS · DOCUMENTATION</div><h1>Welcome to<br/><span>House of Stars.</span></h1><p className="docs-lead">A practical guide to exchanging supported digital assets, including Telegram Stars, through the House of Stars Telegram bot and Mini App.</p><div className="docs-callout"><span>✦</span><p>House of Stars availability, quotes, supported assets, and payout methods may change. Review the current terms and quote shown in the Mini App before confirming an order.</p></div></section>
        <section id="how-it-works" className="docs-section"><div className="docs-eyebrow">01 / THE EXCHANGE</div><h2>How it works</h2><p>Start in the official Telegram bot, choose a supported asset and follow the order flow shown in the Mini App. Review the quote and settlement instructions before you confirm. The app will show the next action and any status updates for your order.</p><div className="docs-steps">{[['01','Open','Start the official House of Stars bot in Telegram and launch its Mini App.'],['02','Review','Choose the asset and amount. Check the quote, payout details, and any requirements shown.'],['03','Confirm','Follow the in-app instructions and monitor the order status in the Mini App or bot chat.']].map(([n,t,d])=><div key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></section>
        <section id="sell-stars" className="docs-section"><div className="docs-eyebrow">02 / STEP-BY-STEP GUIDE</div><h2>Sell Telegram Stars</h2><p>Use the Mini App launched from the official House of Stars bot to create and track a Stars sale. The Mini App displays the current supported flow and quote for your account.</p><ol className="docs-list"><li><span>Open the official bot</span><p>Go to <a href="https://t.me/houseofstarsorderbot" target="_blank" rel="noreferrer">@houseofstarsorderbot</a> in Telegram. Check the username carefully, then tap <strong>Start</strong>.</p></li><li><span>Launch the Mini App</span><p>Tap the Mini App or exchange button in the bot chat. Keep the process inside this official bot and its launched app.</p></li><li><span>Choose the Stars selling flow</span><p>In the Mini App, select the option to sell Telegram Stars. Enter the amount you want to sell and review the quote, minimums, fees (if shown), and estimated payout.</p></li><li><span>Provide the requested details</span><p>Follow the app’s prompts for any required Telegram account, order, or payout information. Only enter details requested in the official Mini App.</p></li><li><span>Confirm and complete the transfer</span><p>Read the order instructions in full. If the app asks you to transfer Stars, use the exact recipient and amount shown for your order. Do not send Stars to a different account or reuse an old payment instruction.</p></li><li><span>Track settlement</span><p>Return to the Mini App or bot chat to check the order status and follow any additional verification steps. Keep the order reference until the payout is complete.</p></li></ol><div className="docs-warning"><strong>Before you confirm</strong><p>Check the recipient, amount, quote, and payout destination shown for this specific order. Never share Telegram login codes, passwords, or wallet recovery phrases with anyone claiming to provide support.</p></div></section>
        <section id="safety" className="docs-section"><div className="docs-eyebrow">03 / HELP</div><h2>Safety & support</h2><p>Use the official bot linked on this page to start an order. House of Stars will show the available support route in the bot or Mini App. Include your order reference when asking about an existing order, and never send credentials or recovery phrases.</p></section>
        <section id="roadmap" className="docs-section docs-roadmap"><div className="docs-eyebrow">04 / WHAT’S AHEAD</div><h2>Roadmap</h2><div className="roadmap-quarter"><span>Q4</span><div><h3>2026</h3><p>Planned focus areas</p></div></div><ul><li>TON network integration</li><li>Gift cards integration</li><li>10 project partnerships</li></ul><p className="roadmap-note">Roadmap items are plans and may change as development progresses.</p></section>
        <footer className="docs-footer"><span>HOUSE OF STARS · DOCS</span><a href="https://t.me/houseofstarsorderbot" target="_blank" rel="noreferrer">Open the Mini App <ArrowUpRight size={14}/></a></footer>
      </main>
      <aside className="docs-onpage"><span>ON THIS PAGE</span>{['overview','how-it-works','sell-stars','safety','roadmap'].map((id,i)=><button key={id} onClick={()=>navigate(id)} className={active===id?'active':''}>{['Overview','How it works','Sell Telegram Stars','Safety & support','Roadmap'][i]}</button>)}</aside>
    </div>
  </div>;
}
